# Generated by Django 4.0.5 on 2022-06-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_description_product_box_product_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minprice',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='box',
            field=models.CharField(default='Updating...', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Updating...', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='camera',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.CharField(default='Updating...', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='chip',
            field=models.CharField(default='Updating...', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Updating...', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='os',
            field=models.CharField(default='Updating...', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='screenres',
            field=models.CharField(default='Updating...', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='screensize',
            field=models.CharField(default='Updating...', max_length=200),
        ),
    ]
