# Generated by Django 4.0.5 on 2022-06-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_product_minprice_alter_product_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('AP', 'Apple'), ('SS', 'Samsung')], default='Apple', max_length=20),
        ),
    ]
