# Generated by Django 4.0.5 on 2022-06-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('AP', 'Apple'), ('SS', 'Samsung')], default='AP', max_length=20),
        ),
    ]
