# Generated by Django 4.0.5 on 2022-06-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='path',
            field=models.SlugField(default=models.CharField(default='Updating...', max_length=200)),
        ),
    ]
