# Generated by Django 4.0.5 on 2022-06-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='path',
            field=models.SlugField(default=''),
        ),
    ]
