# Generated by Django 4.0.5 on 2022-06-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='camera',
            field=models.CharField(default='Updating...', max_length=200),
        ),
    ]
